{
 "title": "Exemplar",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Service Up/Down",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    { "expr": "sum by (job) (up)", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Requests per Minute",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (path) (rate (requests_total[1m])) * 60",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (path) (rate(request_duration_histogram_bucket{}[1m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Requests per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (path) (rate(requests_total[1m]) * 60)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "sum by (path) (rate( {job=\"tomcat-access\"} | pattern `<_> - - <_> \"<method> <path> <_>\" <status> <size>` != \"/metrics\" | status !=200 [1m])) / sum by (path) (rate( {job=\"tomcat-access\"} | pattern `<_> - - <_> \"<method> <path> <_>\" <status> <size>` != \"/metrics\" [1m])) * 100",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (path) (rate(request_duration_histogram_bucket{}[1m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "90% Percentile",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "quantile_over_time (0.90, {job=\"tomcat-access\"} | pattern `<_> - - <_> \"<method> <path> <_>\" <status> <size>` != \"/metrics\" | unwrap size [1m] ) by (path)"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{job=\"hello-observability\"}"
    }
   ]
  }
 ]
}