# This file serves as the agent configuration to interact with the
# docker compose environment.
#
# You should pass the following command line flags when running the agent
# locally and using this file:
#
#   -enable-features=integrations-next -config.expand-env -config.enable-read-api
#
# -enable-features=integrations-next is required as the file is configured for
# the integrations revamp.
#
# -config.expand-env is required to expand environment variables. Environment
# variables are used when running the agent inside of docker-compose to connect
# to the other services. When running the agent externally, the expressions will
# default to the appropriate values of the exposed ports.
#
# -config.enable-read-api is optional, but allows you to invoke the /-/config
# endpoint to examine the generated config.

server:
  log_level: debug
  http_listen_port: 12345

#integrations:
#  node_exporter:
#    enabled: true
#    rootfs_path: /host/root
#    sysfs_path: /host/sys
#    procfs_path: /host/proc

logs:
  configs:
  - name: default
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
      - job_name: hello-observability
        static_configs:
          - targets: [localhost]
            labels:
              job: hello-observability
              __path__: /tmp/hello-observability.log
      - job_name: tomcat-access
        static_configs:
          - targets: [localhost]
            labels:
              job: tomcat-access
              __path__: /tmp/access_log.log

    clients:
      - url: https://logs-prod3.grafana.net/loki/api/v1/push
        basic_auth:
          username: 164126
          password: eyJrIjoiMGMzMWIwZGNkNWQzYjljZDkxM2E5ZDJhODIxYTQ5YWIxZTA0NDdhYiIsIm4iOiJ0ZXN0LWxvZ3MiLCJpZCI6NjAxMzgwfQ==
    target_config:
      sync_period: 10s

traces:
  configs:
  - name: default
    automatic_logging:
      backend: stdout
      roots: true
    remote_write:
      - endpoint: tempo-us-central1.grafana.net:443
        basic_auth:
          username: 160639
          password: eyJrIjoiYjkzMDA1NDE0ODRhYWRjYzgwNjg0YTJlNzcyZmY0MThmMDNiOTRjMiIsIm4iOiJ0ZXN0IiwiaWQiOjYwMTM4MH0=
    receivers:
      otlp:
        protocols:
          grpc:

metrics:
  configs:
  - name: hello-observability
    remote_write:
    - basic_auth:
        username: 330312
        password: eyJrIjoiZjRlZGVhYmMzZDg2NTQ3ODExMDJkYTg0M2RiMjAyZTU3N2JjZDQzNiIsIm4iOiJ0ZXN0LW1ldHJpY3MiLCJpZCI6NjAxMzgwfQ==
      url: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
    scrape_configs:
    - job_name: hello-observability
      scrape_interval: 10s
      static_configs:
      - targets:
        - hello-observability:8080
      metric_relabel_configs:
        - source_labels: [ 'trace_id' ]
          target_label: 'traceID'

  global:
    scrape_interval: 10s
    external_labels:
      monitor: hello-observability
  wal_directory: /tmp/grafana-agent-wal
