global:
  scrape_interval:     10s
  external_labels:
    monitor: hello-observability

scrape_configs:
  - job_name: hello-observability
    scrape_interval: 10s
    static_configs:
      - targets: [hello-observability:8080]
